<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>Vanadreams</RootNamespace>
    <AssemblyName>VanadreamsLauncher</AssemblyName>
    <AssemblyTitle>Vanadreams Launcher</AssemblyTitle>
    <Product>Vanadreams Launcher</Product>
    <Version>0.2.21</Version>
    <ApplicationIcon>assets\moon.ico</ApplicationIcon>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Security" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="assets\**\*" />
  </ItemGroup>
</Project>
